---
- name: Copy the node_exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node_exporter
    - systemd_reload
  when: ansible_service_mgr == "systemd"

- block:
  - name: Copy the node_exporter init script
    template:
      src: node_exporter_sysv.j2
      dest: /etc/init.d/node_exporter
      owner: root
      group: root
      mode: 0755

  - name: Copy the node_exporter sysconfig
    template:
      src: node_exporter_sysconfig.j2
      dest: /etc/sysconfig/node_exporter
      owner: root
      group: root
      mode: 0640

  - name: Copy the node_exporter logrotate
    template:
      src: node_exporter_logrotate.j2
      dest: /etc/logrotate.d/node_exporter
      owner: root
      group: root
      mode: 0644

  - name: Allow traffic in iptables
    lineinfile:
      path: /etc/sysconfig/iptables
      regexp: '^-A INPUT.*--dport {{ node_exporter_port }}'
      insertbefore: '^-A INPUT -j REJECT'
      line: '-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ node_exporter_port }} -j ACCEPT'
    notify: reload iptables
    when: node_exporter_iptables

  when: ansible_service_mgr != "systemd"

- block:
    - name: Create node_exporter config directory
      file:
        path: "/etc/node_exporter"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy the node_exporter config file
      template:
        src: config.yaml.j2
        dest: /etc/node_exporter/config.yaml
        owner: root
        group: root
        mode: 0644
      notify: restart node_exporter
  when:
    ( node_exporter_tls_server_config | length > 0 ) or
    ( node_exporter_http_server_config | length > 0 ) or
    ( node_exporter_basic_auth_users | length > 0 )

- name: Create textfile collector dir
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
    recurse: true
    mode: u+rwX,g+rwX,o=rX
  when: node_exporter_textfile_dir | length > 0

- name: Allow node_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
