---
- name: restart node_exporter
  become: true
  service:
    name: node_exporter
    state: restarted
  when:
    - not ansible_check_mode

- name: systemd_reload
  become: true
  systemd:
    daemon_reload: yes
  when:
    - not ansible_check_mode

- name: reload iptables
  become: true
  service:
    name: iptables
    state: reloaded
